# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Card' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Card
  pod 'ReSwift'
  pod 'RealmSwift', '~> 2.10.1' 


  target 'CardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
